let lang = "Marathi";

if(localStorage.lang) {
    lang = localStorage.getItem("lang")
}

const LANG = {
    APP_NAME: lang == "English" ? "Agrowon Animal Care" : "अ‍ॅग्रोगोथा",
    BLOG_POST: lang == "English" ? "News and feeds" : "बातम्या आणि फीड",
    FEEDBACK: lang == "English" ? "Feeback " : "अभिप्राय",
    REPLIES: lang == "English" ? "Replies" : "प्रत्युत्तरे",
    ANIMAL: lang == "English" ? "Animal" : "प्राणी व्यवस्थापक",
    FARM: lang == "English" ? "Farm" : "बातम्या आणि फीड",
    USERS: lang == "English" ? "Farmer Management" : "वापरकर्ता व्यवस्थापक",
    ANIMAL_CATEGORY: lang == "English" ? "Animal Types" : "प्राण्यांचा प्रकार",
    DASHBOARD: lang == "English" ? "Dashboard" : "मुख्यपृष्ठ",
    CSE: lang == "English" ? "Customer Service Executive" : "ग्राहक सेवा कार्यकारी",
    ADMIN: lang == "English" ? "ADMIN" : "प्रशासन",
    PROFILE: lang == "English" ? "Profile" : "प्रोफाइल",
    MY_ACCOUNT: lang == "English" ? "Profile" : "माझे खाते",
    LOGOUT: lang == "English" ? "Logout" : "बाहेर पडणे",
    SEARCH_HERE: lang == "English" ? "Search Here" : "येथे शोधा",
    LOGIN: lang == "English" ? "Login" : "लॉगिन",
    PHONE_NUMEBR: lang == "English" ? "Phone Number" : "फोन नंबर",
    PASSWORD: lang == "English" ? "Password" : "संकेतशब्द",
    LOADING: lang == "English" ? "Loading ..." : "लोड करीत आहे ..",
    NUMBER_OF_USERS: lang == "English" ? "Number Of Users" : "वापरकर्त्यांची संख्या",
    MONTH_USERS: lang == "English" ? "Month Users" : "महिना वापरकर्ते",
    ACTIVE_USERS: lang == "English" ? "Number of active users" : "सक्रिय वापरकर्त्यांची संख्या",
    ANIMAL_LIST: lang == "English" ? "Personal list of animals" : "प्राण्यांची वैयक्तिक यादी",
    TOTAL_FARMS: lang == "English" ? "Total number of farms" : "एकूण शेती संख्या",
    TOTAL_ANIMALS: lang == "English" ? "Total number of animals" : "एकूण प्राण्यांची संख्या",
    ACRE_AREA: lang == "English" ? "Acre area" : "एकर क्षेत्रफळ",
    DOWNLOADS: lang == "English" ? "Total app downloads" : "एकूण अ‍ॅप डाउनलोड",
    WELCOME: lang == "English" ? "Welcome" : "स्वागत आहे",
    SLNO: lang == "English" ? "Sl No" : "स्ल न",
    TITLE: lang == "English" ? "Title" : "शीर्षक",
    CREATEDAT: lang == "English" ? "CreatedAt" : "तयार केलेले",
    ADDEDBY: lang == "English" ? "Added By" : "जोडले",
    ACTION: lang == "English" ? "Action" : "जोडले",
    SHOWENTRIES: lang == "English" ? "Show Entires" : "नोंदी दर्शवा",
    ADD: lang == "English" ? "Add" : "जोडा",
    EDIT: lang == "English" ? "Edit" : "सुधारणे",
    ALL: lang == "English" ? "All" : "सर्व",
    VIEW: lang == "English" ? "View" : "पहा", 
    DELETE: lang == "English" ? "Delete" : "हटवा", 
    PICTURE: lang == "English" ? "Picture" : "चित्र", 
    UPDATE: lang == "English" ? "Update" : "अद्ययावत",
    REPLY: lang == "English" ? "Reply" : "उत्तर द्या", 
    ANIMAL_TYPE: lang == "English" ? "Animal Type" : "मूळ प्रकार", 
    FARMER: lang == "English" ? "Farmer" : "फार्म", 
    EMAIL: lang == "English" ? "Email" : "ईमेल", 
    NAME: lang == "English" ? "Name" : "नाव", 
    COUNT: lang == "English" ? "Count" : "मोजा", 
    PASSWORD: lang == "English" ? "Password" : "संकेतशब्द", 
    PINCODE: lang == "English" ? "Pincode" : "पिन कोड", 
    ADDRESS: lang == "English" ? "Address" : "पत्ता", 
    TOTAL_AREA: lang == "English" ? "Total Area" : "एकूण क्षेत्र", 
    TYPE: lang == "English" ? "Type" : "प्रकार", 
    ANIMAL_BREED: lang == "English" ? "Animal Breed" : "पशु नस्ल", 
    TAG_NUMBER: lang == "English" ? "Tag Number" : "टॅग क्रमांक", 
    DOB: lang == "English" ? "DOB" : "जन्म तारीख", 
    WEIGHT: lang == "English" ? "Weight" : "वजन", 
    PREGNANT: lang == "English" ? "Pregnant" : "गर्भवती", 
    LOCATING: lang == "English" ? "Locating" : "शोधत आहे", 
    BORN_IN_DAIRY: lang == "English" ? "Born in DAIRY" : "डेअरी मध्ये जन्म", 
    PRICE: lang == "English" ? "Purchasing Price" : "किंमत खरेदी", 
    YES: lang == "English" ? "YES" : "होय", 
    NO: lang == "English" ? "NO" : "नाही", 
    FARMER_LIST: lang == "English" ? "Farmer List" : "शेतकरी यादी", 
    FARMER_DETAILS: lang == "English" ? "Farmer Details" : "शेतकरी तपशील", 
    BLOG_LIST: lang == "English" ? "News and feeds List" : "बातम्या आणि फीडची यादी", 
    ANIMAL_TYPE_LIST: lang == "English" ? "Animal Type List" : "प्राचिन प्रकार यादी", 
    LIST: lang == "English" ? "List" : "यादी", 
    QR_CODE: lang == "English" ? "Qr Code" : "QR कोड"
}
export default LANG;